---

- name: "LOOPS"
  hosts: cisco
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "TASK I - LOOP THROUGH NTP SERVERS"
      vars:
        myservers:
          - "1.1.1.1"
          - "2.2.2.2"
          - "3.3.3.3"
          - "4.4.4.4"
      cisco.ios.ntp_global:
        config:
          peers:
            - peer: "{{ item }}"
              version: 2
      loop: "{{ myservers }}"
